### ISSUE TITLE
Petr Paleta: Co programátory ve škole neučí aneb Softwarové inženýrství v reálné praxi

### ISSUE THREAD

**Issue by jsuchal** [rubyslava/bookshelf#21]
Poslane na RailsGirls do Ziliny. Zodpovedny je @harcek.

**Comment by jsuchal** [comment]
@jangondol review bude?

**Comment by jangondol** [comment]
@jsuchal Komplexnú recenziu z toho s niekoľkomesačným odstupom neurobím. Pamätám si ale, že knižka sa mi zdala fajn prehľadom princípov vývoja softvéru (trebárs pre študentov informatiky alebo aj "samoštudentov"), akurát že miestami bolo trošku cítiť, že vznikla v trochu inom svete, v ktorom ešte neexistovali Git, AWS, neriešil sa DevOps,... Mrazí ma z toho, že autor knižky zomrel mladý, v našom veku -- aktualizovanú verziu už nenapíše. Väčšina princípov, o ktorých sa hovorí, sú však nadčasové.
