### ISSUE TITLE
Functional Programming in Java: Harnessing the Power of Java 8 Lambda Expressions

### ISSUE THREAD

**Issue by tomashaber** [rubyslava/bookshelf#41]

**Comment by jsuchal** [comment]
@tomashaber ako to vyzera?

**Comment by tomashaber** [comment]
Review je tu uz nejaky cas : https://github.com/rubyslava/bookshelf/blob/master/reviews/functional-rogramming-in-java.md

**Comment by jsuchal** [comment]
@tomashaber vyborne, diky.
