### ISSUE TITLE
PostGIS in Action review

### ISSUE THREAD

**Issue by m1k3** [rubyslava/bookshelf#49]
aby som nezabudol, tak si to semkaj pisem.

**Comment by jsuchal** [comment]
@m1k3 citas este?

**Comment by m1k3** [comment]
mam to v taskoch, ale nejde sa mi k tomu prepracovat. Ak chces tak toto mozes zavriet a ja to znovuotvorim ked sa k tomu dostanem...

**Comment by jsuchal** [comment]
@m1k3 vidis to realne niekedy v blizkej dobe?

**Comment by m1k3** [comment]
Tak po par rokoch, ale predsa :) #107
