### ISSUE TITLE
Go in Action

### ISSUE THREAD

**Issue by jbub** [rubyslava/bookshelf#61]
Cakam na ebook, ked precitam slubujem review.

**Comment by jsuchal** [comment]
@jbub ako to vyzera teraz?

**Comment by jbub** [comment]
Ahoj akurat dnes vysla MEAP v9, kde pridali poslednu sekciu "TESTING AND BENCHMARKING", takze v blizkej docitam a pustim sa do review.

**Comment by jsuchal** [comment]
:+1:
