### ISSUE TITLE
Soft Skills

### ISSUE THREAD

**Issue by martinliptak** [rubyslava/bookshelf#97]

**Comment by jsuchal** [comment]
@kremso @crutch je to na Liptovskej?

**Comment by crutch** [comment]
Nevidim tu nic, co by malo v nazve soft skills. Co to ma byt presne za knihu?

**Comment by crutch** [comment]
Tak uz som zistil, ze tato: https://www.manning.com/books/soft-skills. Ale nevidim ju na Liptovskej. @alenkacz z #76 davala si ju niekomu?

**Comment by martinliptak** [comment]
Áno, presne tá. Videl som recenziu vo FB skupine.

https://github.com/rubyslava/bookshelf/blob/master/reviews/soft-skills.md

**Comment by jsuchal** [comment]
Bol to len ebook.
